<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Finance.Domain\Finance.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Finance.Tests" />
  </ItemGroup>

</Project>
